PrediosEjido/apps/principal/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('PrediosEjido.apps.principal.views',
	url(r'^$', 'home', name = 'home'),
	url(r'^Importar/$', 'upload_data_predio', name = 'upload_data_predio'),
	url(r'^Predios/$', 'list_predio', name = 'list_predio'),
	url(r'^Predios/Ver/(?P<predio_pk>\d+)/$', 'view_predio', name = 'view_predio'),
	url(r'^Predios/Nuevo/(?:/(?P<predio_pk>\d+))?', 'predio', name = 'predio'),
	url(r'^Predios/Propietario/(?P<predio_pk>\d+)/$', 'sold_predio', name = 'sold_predio'),
	url(r'^Predios/Eliminar/(?P<predio_pk>\d+)/$', 'delete_predio', name = 'delete_predio'),
	url(r'^Predios/Reportes/all-predio/(?:/(?P<option>\d+))?', PredioAllPDFView.as_view(), name = 'pdf_all_predio'),
	url(r'^Propietarios/$', 'list_propieta', name = 'list_propieta'),
	url(r'^Propietarios/Nuevo/(?:/(?P<propieta_pk>\d+))?', 'propietario', name = 'propietario'),
	url(r'^Propietarios/Eliminar/(?P<propieta_pk>\d+)/$', 'delete_propieta', name = 'delete_propieta'),
	url(r'^Logout/$', 'logout_user', name = 'logout_user'),
	url(r'^Usuarios/$', 'list_user', name = 'list_user'),
	url(r'^Usuarios/Nuevo/$', 'user', name = 'user'),
)

PrediosEjido/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('PrediosEjido.apps.principal.urls')),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', name = 'login'),
]

PrediosEjido/apps/principal/models.py
from django.db import models

class Propieta(models.Model):
	id_propieta = models.CharField(max_length = 15)
	name = models.CharField(max_length = 30)
	def __unicode__(self):
		return self.id_propieta+' '+self.name

class Predio(models.Model):
	c_catastral = models.CharField(max_length = 15)
	t_ord = models.CharField(max_length = 3)
	t_tot = models.CharField(max_length = 3)
	propieta = models.CharField(max_length = 50)
	e = models.CharField(max_length = 1, blank = True, null = True)
	d = models.CharField(max_length = 1, blank = True, null = True)
	id_propietario = models.CharField(max_length = 15, default = '0')
	dir_predio = models.CharField(max_length = 30)
	hectarea = models.IntegerField(default = 0)
	met2 = models.IntegerField()
	area_con = models.IntegerField(default = 0)
	avaluo_catastral = models.DecimalField(max_digits = 11, decimal_places = 2)
	c_recaja = models.IntegerField(blank = True, null = True)
	f_recaja = models.DateField(auto_now = False, blank = True, null = True)
	v_recaja = models. DecimalField(max_digits = 11, decimal_places = 2, blank = True, null = True)
	id_propieta_fin = models.ForeignKey(Propieta, blank = True, null = True)
	def __unicode__(self):
		return str(self.pk)

PrediosEjido/apps/principal/forms.py
# -*- encoding: utf-8 -*-
from django.contrib.auth.models import User
from django.forms import *
from django import forms
from .models import *

class PredioForm(forms.ModelForm):
	class Meta:
		model = Predio
		fields = '__all__'
		exclude = ('c_recaja', 'f_recaja', 'v_recaja', 'id_propieta_fin')
		widgets = {
			'c_catastral': TextInput(attrs = {'class': 'form-control number-val', 'maxlength': '15', 'required': True}),
			't_ord': TextInput(attrs = {'class': 'form-control number-val', 'maxlength': '3', 'required': True}),
			't_tot': TextInput(attrs = {'class': 'form-control number-val', 'maxlength': '3', 'required': True}),
			'propieta': TextInput(attrs = {'class': 'form-control', 'maxlength': '9', 'required': True}),
			'e': TextInput(attrs = {'class': 'form-control', 'maxlength': '1'}),
			'd': TextInput(attrs = {'class': 'form-control', 'maxlength': '1'}),
			'id_propietario': TextInput(attrs = {'class': 'form-control', 'maxlength': '15', 'required': True}),
			'dir_predio': TextInput(attrs = {'class': 'form-control', 'maxlength': '30', 'required': True}),
			'hectarea': TextInput(attrs = {'class': 'form-control number-val'}),
			'met2': TextInput(attrs = {'class': 'form-control number-val', 'required': True}),
			'area_con': TextInput(attrs = {'class': 'form-control number-val'}),
			'avaluo_catastral': TextInput(attrs = {'class': 'form-control number-val', 'maxlength': '9', 'required': True})
		}
		labels = {
			'c_catastral': 'Código Catastral',
			't_ord': 'ORD',
			't_tot': 'TOT',
			'propieta': 'Nombre del Propietario',
			'e': 'E',
			'd': 'D',
			'id_propietario': 'Identificación del Propietario',
			'dir_predio': 'Dirección del Predio',
			'hectarea': 'Tamaño en Hectárea',
			'met2': 'Tamaño en Metros',
			'area_con': 'Tamaño de Área Construida',
			'avaluo_catastral': 'Valor Avaluo Catastral'
		}

class PropietarioVentaForm(forms.Form):
	c_recaja = forms.CharField(label = 'Código Recibo de Caja', widget = forms.TextInput(attrs = {'required': True, 'class': 'form-control number-val'}))
	f_recaja = forms.CharField(label = 'Fecha del Recibo de Caja', widget = forms.TextInput(attrs = {'required': True, 'class': 'form-control datepicker'}))
	v_recaja = forms.CharField(label = 'Valor Recibo de Caja', widget = forms.TextInput(attrs = {'required': True, 'class': 'form-control number-val', 'maxlength': '9'}))
	id_propieta_fin = forms.ModelChoiceField(label = 'Propietario', queryset = Propieta.objects.all(), widget = forms.Select(attrs = {'class': 'form-control', 'required': True}))
	id_propieta = forms.CharField(label = 'Identificación del propietario', widget = forms.TextInput(attrs = {'class': 'form-control', 'maxlength': '15'}))
	name = forms.CharField(label = 'Nombre Completo del propietario', widget = forms.TextInput(attrs = {'class': 'form-control', 'maxlength': '30'}))

class UploadForm(forms.Form):
	file_input = forms.FileField()

	def upload(self):
		val = 0
		text = self.cleaned_data.get('file_input')
		for txt in text.readlines():
			predio_array = []
			val = txt.replace('\n', '').replace(',', '')
			for v in val.split(" "):
				predio_array.append(v)
			predio = Predio(c_catastral = predio_array[0], t_ord = predio_array[1], t_tot = predio_array[2], propieta = predio_array[3].replace('-', ' '), e = predio_array[4], d = predio_array[5], id_propietario = predio_array[6], dir_predio = predio_array[7].replace('-', ' '), hectarea = int(predio_array[8]), met2 = int(predio_array[9]), area_con = int(predio_array[10]), avaluo_catastral = int(predio_array[11]))
			predio.save()
		return "Importación Exitoso"

class PropietaForm(forms.ModelForm):
	class Meta:
		model = Propieta
		fields = '__all__'
		widgets = {
			'id_propieta': TextInput(attrs = {'class': 'form-control', 'maxlength': '15', 'required': True}),
			'name': TextInput(attrs = {'class': 'form-control', 'maxlength': '30', 'required': True}),
		}
		labels = {
			'id_propieta': 'Identificación del propietario',
			'name': 'Nombre Completo del propietario',
		}

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = '__all__'
		widgets = {
			'password': TextInput(attrs = {'class': 'form-control', 'type': 'password', 'required': True}),
			'username': TextInput(attrs = {'class': 'form-control', 'required': True}),
			'first_name': TextInput(attrs = {'class': 'form-control', 'required': True}),
		}
		labels = {
			'password': 'Contraseña',
			'username': 'Username',
			'first_name': 'Nombre del Usuario',
		}
		exclude = ('last_login', 'groups', 'user_permissions', 'last_name', 'email', 'date_joined', 'is_staff', 'is_active', 'is_superuser')

PrediosEjido/apps/principal/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from easy_pdf.views import PDFTemplateView
from django.contrib.auth import logout
from django.shortcuts import render
from django.db.models import Sum
from .models import Predio
from .forms import *
import json

@login_required
def home(request):
	return render(request, 'home.html', {'title': 'Bienvenido'})

@login_required
def list_predio(request):
	predios = Predio.objects.all()
	return render(request, 'list-predio.html', {'title': 'Listado de Predios', 'predios': predios})

def view_predio(request, predio_pk):
	predio = Predio.objects.get(pk = predio_pk)
	return render(request, 'show-predio.html', {'title': 'Detalle del Predio', 'predio': predio})

def predio(request, predio_pk = 0):
	try:
		predio = Predio.objects.get(pk = predio_pk)
	except Predio.DoesNotExist:
		predio = predio_pk
	if request.method == 'POST':
		response = {}
		form = PredioForm(request.POST, instance = predio)
		if form.is_valid():
			if predio != 0:
				response['sold'] = True
			else:
				response['sold'] = False
			predio_data = form.save()
			response['pk'] = predio_data.pk
			response['c_catastral'] = predio_data.c_catastral
			response['dir_predio'] = predio_data.dir_predio
			response['hectarea'] = predio_data.hectarea
			response['met2'] = predio_data.met2
			response['avaluo_catastral'] = str(predio_data.avaluo_catastral)
		else:
			response['response'] = "Ha ocurrido un error"
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = PredioForm(instance = predio)
	return render(request, 'form-predio.html', {'title': 'Nuevo Predio', 'predio_val': predio, 'forms': form})

def sold_predio(request, predio_pk):
	predio = Predio.objects.get(pk = predio_pk)
	if request.method == 'POST':
		response = {}
		predio.c_recaja = request.POST['c_recaja']
		predio.f_recaja = request.POST['f_recaja']
		predio.v_recaja = request.POST['v_recaja']
		if request.POST['id_propieta'] != "" and request.POST['id_propieta_fin'] == "":
			propieta = Propieta(id_propieta = request.POST['id_propieta'], name = request.POST['name'])
			propieta.save()
		else:
			propieta = Propieta.objects.get(pk = request.POST['id_propieta_fin'])
		predio.id_propieta_fin = propieta
		predio.save(update_fields = ['c_recaja', 'f_recaja', 'v_recaja', 'id_propieta_fin'])
		response['response'] = predio.pk
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = PropietarioVentaForm()
	return render(request, 'sold-predio.html', {'title': 'Nuevo Propietario de Predio', 'forms': form, 'predio_pk': predio_pk})

def delete_predio(request, predio_pk):
	response = {}
	predio = Predio.objects.get(pk = predio_pk)
	response['response'] = predio.pk
	predio.delete()
	return HttpResponse(json.dumps(response), content_type = 'application/json')

class PredioAllPDFView(PDFTemplateView):
	template_name = "pdf_all_predio.html"

	def get_context_data(self, **kwargs):
		context = super(PredioAllPDFView, self).get_context_data(**kwargs)
		context['option'] = self.kwargs['option']
		if context['option'] == "1":
			predios = Predio.objects.exclude(c_recaja__isnull = True)
		else:
			predios = Predio.objects.all()
		context['predios'] = predios
		context['cont'] = 0
		context['total'] = predios.aggregate(avaluo_catastral_sum = Sum('avaluo_catastral'))
		context['title'] = 'Listado de Predios y Propietarios'
		return context

def upload_data_predio(request):
	message = ""
	type_m = ""
	if request.method == 'POST':
		form = UploadForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			if form.upload():
				message = "Importacion Exitosa"
				type_m = "success"
			else:
				message = "Ha Ocurrido un Error"
				type_m = "danger"
	else:
		form = UploadForm()
	return render(request, 'importer.html', {'title': 'Importar', 'form': form, 'message': message, 'type_m': type_m})

def propietario(request, propieta_pk):
	try:
		propieta = Propieta.objects.get(pk = propieta_pk)
		propieta_val = propieta.pk
	except Propieta.DoesNotExist:
		propieta = propieta_pk
		propieta_val = propieta
	if request.method == 'POST':
		response = {}
		form = PropietaForm(request.POST, instance = propieta)
		if form.is_valid():
			if propieta != 0:
				response['sold'] = True
			else:
				response['sold'] = False
			propieta_data = form.save()
			response['pk'] = propieta_data.pk
			response['id_propieta'] = propieta_data.id_propieta
			response['name'] = propieta_data.name
		else:
			response['response'] = "Ha ocurrido un error"
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = PropietaForm(instance = propieta)
	return render(request, 'form-propieta.html', {'title': 'Nuevo Propietario', 'propieta_val': propieta_val, 'forms': form})

def delete_propieta(request, propieta_pk):
	response = {}
	propieta = Propieta.objects.get(pk = propieta_pk)
	response['response'] = propieta.pk
	propieta.delete()
	return HttpResponse(json.dumps(response), content_type = 'application/json')

@login_required
def list_propieta(request):
	propietas = Propieta.objects.all()
	return render(request, 'list-propieta.html', {'title': 'Listado de Propietarios', 'propietas': propietas})

def logout_user(request):
	logout(request)
	return HttpResponseRedirect('/')

@user_passes_test(lambda u: u.is_superuser)
def list_user(request):
	users = User.objects.all()
	return render(request, 'list-user.html', {'title': 'Listado de Usuarios', 'users': users})

def user(request):
	if request.method == 'POST':
		response = {}
		form = UserForm(request.POST)
		if form.is_valid():
			user_data = User.objects.create_user(**form.cleaned_data)
			response['pk'] = user_data.pk
			response['username'] = user_data.username
			response['first_name'] = user_data.first_name
		else:
			response['response'] = "Ha ocurrido un error"
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = UserForm()
	return render(request, 'form-user.html', {'title': 'Nuevo Propietario', 'forms': form})

PrediosEjido/apps/principal/templates/form-predio.html
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">{{ title }}</h4>
		</div>
		<form action="{% url 'predio' predio_val %}" method="POST">
			{% csrf_token %}
			<div class="modal-body">
				<div class="row">
					{% for form in forms %}
						<div class="col-md-6">
							<div class="form-group">
								<label>{{ form.label }}</label>
								{{ form }}
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<input type="submit" value="Guardar" class="btn btn-success"/>
			</div>
		</form>
	</div>
</div>

<script>
	$(function() {
		$('.form-group').on('keydown', '.number-val', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
	})
	$("form").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				$('.'+data.pk).remove();
				$('#table-predio tbody').append(
					"<tr class='"+data.pk+"'>"+
						"<td>"+data.c_catastral+"</td>"+
						"<td>"+data.dir_predio+"</td>"+
						"<td>"+data.hectarea+"</td>"+
						"<td>"+data.met2+"</td>"+
						"<td>$ "+Number(data.avaluo_catastral).toLocaleString('en')+"</td>"+
						"<td class='action-"+data.pk+"'></td>"+
					"</tr>"
				);
				if(data.sold == true){
					$('.action-'+data.pk).append("<a href='/Predios/Propietario/"+data.pk+"/' class='btn btn-success open-modal sold-"+data.pk+"'>Venta</a>");
				}else{
					$('.'+data.pk).addClass("success");
				}
				$('.action-'+data.pk).append(
					"<a href='/Predios/Ver/"+data.pk+"' class='btn btn-primary open-modal'>Detalle</a>"+
					"{% if user.is_superuser %}<a href='/Predios/Eliminar/"+data.pk+"/' class='btn btn-danger delete'>Eliminar</a>{% endif %}"+
					"<a href='/Predios/Nuevo//"+data.pk+"' class='btn btn-default open-modal'>Editar</a>"
				);
				$('#Modal').modal('hide');
			}
		});
	});
</script>

PrediosEjido/apps/principal/templates/form-propieta.html
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">{{ title }}</h4>
		</div>
		<form action="{% url 'propietario' propieta_val %}" method="POST">
			{% csrf_token %}
			<div class="modal-body">
				<div class="row">
					{% for form in forms %}
						<div class="col-md-12">
							<div class="form-group">
								<label>{{ form.label }}</label>
								{{ form }}
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<input type="submit" value="Guardar" class="btn btn-success"/>
			</div>
		</form>
	</div>
</div>

<script>
	$("form").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				$('.'+data.pk).remove();
				$('#table-propieta tbody').append(
					"<tr class='"+data.pk+"'>"+
						"<td>"+data.id_propieta+"</td>"+
						"<td>"+data.name+"</td>"+
						"<td>"+
							"{% if user.is_superuser %}<a href='/Propietarios/Eliminar/"+data.pk+"' class='btn btn-danger delete'>Eliminar</a>{% endif %}"+
							"<a href='/Propietarios/Nuevo//"+data.pk+"' class='btn btn-default open-modal'>Editar</a>"+
						"</td>"+
					"</tr>"
				);
				$('#Modal').modal('hide');
			}
		});
	});
</script>

PrediosEjido/apps/principal/templates/form-user.html
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">{{ title }}</h4>
		</div>
		<form action="{% url 'user' %}" method="POST">
			{% csrf_token %}
			<div class="modal-body">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label>{{ forms.first_name.label }}</label>
							{{ forms.first_name }}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label>{{ forms.username.label }}</label>
							{{ forms.username }}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label>{{ forms.password.label }}</label>
							{{ forms.password }}
						</div>
					</div>
					<div class="col-md-12">
						<div class="col-md-6">
							<div class="form-group">
								<label>{{ forms.is_superuser.label }}</label>
								{{ forms.is_superuser }}
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>{{ forms.is_active.label }}</label>
								{{ forms.is_active }}
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<input type="submit" value="Guardar" class="btn btn-success"/>
			</div>
		</form>
	</div>
</div>

<script>
	$('#id_password').val('');
	$("form").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				$('.'+data.pk).remove();
				$('#table-user tbody').append(
					"<tr class='"+data.pk+"'>"+
						"<td>"+data.username+"</td>"+
						"<td>"+data.first_name+"</td>"+
					"</tr>"
				);
				$('#Modal').modal('hide');
			}
		});
	});
</script>

PrediosEjido/apps/principal/templates/home.html
{% extends 'layout/base.html' %}

{% load staticfiles %}

{% block content %}
	{% include 'elements/menu.html' %}
	<div id="page-wrapper">
		<div class="row text-center">
			<img src="{% static 'img/bienvenido.png' %}" style="width: 80%; height: auto; margin-top: 100px;">
		</div>
	</div>
{% endblock content %}

PrediosEjido/apps/principal/templates/importer.html
{% extends 'layout/base.html' %}

{% block content_head %}
	<style>
		input[type=file]{
			margin: 0 auto;
			padding-bottom: 30px;
		}
	</style>
{% endblock content_head %}

{% block content %}
	{% include 'elements/menu.html' %}
	<div id="page-wrapper">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">{{ title }}</h1>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-body">
				{% if message %}
					<div class="alert alert-{{ type_m }} text-center" role="alert">
						{{ message }}
					</div>
				{% endif %}
				<div class="row text-center" style="margin-top: 60px; margin-bottom: 60px;">
					<form action="{% url 'upload_data_predio' %}" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form }}
						<input type="submit" value="Importar" class="btn btn-success"/>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

PrediosEjido/apps/principal/templates/sold-predio.html
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">{{ title }}</h4>
		</div>
		<form action="{% url 'sold_predio' predio_pk %}" method="POST">
			{% csrf_token %}
			<div class="modal-body">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label>{{ forms.c_recaja.label }}</label>
							{{ forms.c_recaja }}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label>{{ forms.f_recaja.label }}</label>
							{{ forms.f_recaja }}
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label>{{ forms.v_recaja.label }}</label>
							{{ forms.v_recaja }}
						</div>
					</div>
					<div class="col-md-6" id="propieta_fin">
						<div class="form-group">
							<label>{{ forms.id_propieta_fin.label }}</label>
							{{ forms.id_propieta_fin }}
						</div>
					</div>
					<div class="new-propieta">
						<div class="col-md-12">
							<div class="col-md-6">
								<div class="form-group">
									<label>{{ forms.id_propieta.label }}</label>
									{{ forms.id_propieta }}
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label>{{ forms.name.label }}</label>
									{{ forms.name }}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="text-center">
					<a href="#" class="btn btn-success add-propieta">Agregar propietario</a>
					<a href="#" class="btn btn-danger close-add-propieta">Cerrar</a>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<input type="submit" value="Guardar" class="btn btn-success"/>
			</div>
		</form>
	</div>
</div>

<script>
	$('.add-propieta').on('click', function(e){
		e.preventDefault();
		$('#id_id_propieta_fin').attr('required', false).hide().val('');
		$('#propieta_fin').hide();
		$('#id_id_propieta').attr('required', true);
		$('#id_name').attr('required', true);
		$('.new-propieta').show();
		$('.close-add-propieta').show();
		$('.add-propieta').hide();
	});
	$('.close-add-propieta').on('click', function(e){
		e.preventDefault();
		$('#id_id_propieta_fin').attr('required', true).show();
		$('#propieta_fin').show();
		$('#id_id_propieta').attr('required', false);
		$('#id_name').attr('required', false);
		$('.new-propieta').hide();
		$('.close-add-propieta').hide();
		$('.add-propieta').show();
	});
	$(function() {
		$('.new-propieta').hide();
		$('.close-add-propieta').hide();
		$(".datepicker").datepicker({dateFormat: 'yy-mm-dd'});
	});
	$(function() {
		$('.form-group').on('keydown', '.number-val', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
	});
	$("form").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				$('.'+data.response).addClass("success");
				$('.sold-'+data.response).remove();
				$('#Modal').modal('hide');
			}
		});
	});
</script>